Repository geops/trafimage-maps, pull requests merged in 2020-10, with the labels that each got.

#816 Handicap new texts
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/HandicapLayerInfo/HandicapLayerInfo.js
  src/popups/HandicapPopup/HandicapPopup.js
Labels: 1.3

#795 Add apiKeyName api parameter
  package.json
  src/WebComponent.js
  src/components/TopicLoader/TopicLoader.js
  src/components/TrafimageMaps/TrafimageMaps.js
  src/examples/Casa/README.md
  src/layers/CasaLayer/CasaLayer.js
  src/layers/RouteLayer/RouteLayer.js
  src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
  src/layers/ZoneLayer/ZoneLayer.js
  yarn.lock
Labels: hotfix

#825 Infos on empty handicap popup
  src/popups/HandicapPopup/HandicapPopup.js
  src/searches/HandicapStopFinder/HandicapStopFinder.js
  src/searches/StopFinder/StopFinder.js
Labels: 1.3

#823 CASA map controls update
  src/components/MapControls/MapControls.js
  src/components/MapControls/MapControls.scss
  src/examples/Casa/casa.css
  src/img/minus.svg
  src/img/plus.svg
  src/img/swissbounds.svg
Labels: CASA

#826 Allow handicap popup content to be read by screen reader
  package.json
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap
  src/popups/HandicapPopup/HandicapPopup.js
  src/popups/HandicapPopup/HandicapPopup.scss
  src/popups/HandicapPopup/HandicapPopupElement.js
  src/popups/HandicapPopup/HandicapPopupElement.test.js
  src/popups/HandicapPopup/__snapshots__/HandicapPopupElement.test.js.snap
  yarn.lock
Labels: 1.3

#827 Replace angebotschrifft layers by a filter
  package.json
  src/components/TopicMenu/TopicMenu.js
  src/components/TrafimageMaps/TrafimageMaps.js
  src/config/layers.js
  src/filters/AusbauFilters/AusbauFilters.js
  src/filters/AusbauFilters/AusbauFilters.test.js
  src/filters/AusbauFilters/__snapshots__/AusbauFilters.test.js.snap
  src/filters/AusbauFilters/index.js
  src/filters/index.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layers/AusbauLayer/AusbauLayer.js
  src/layers/AusbauLayer/AusbauLayer.test.js
  src/layers/AusbauLayer/index.js
  src/themes/default.js
  yarn.lock
Labels: 1.3

#828 Fix casa css
  package.json
  src/examples/Casa/casa.css
Labels: hotfix

#830 Changes css of AubsauFilters 2
  package.json
  src/components/TopicMenu/TopicMenu.js
  src/components/TopicMenu/TopicMenu.scss
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/examples/Casa/casa.css
  src/filters/AusbauFilters/AusbauFilters.js
Labels: 1.3

#831 Update showFilter param with selected value
  src/filters/AusbauFilters/AusbauFilters.js
  src/filters/AusbauFilters/AusbauFilters.test.js
  src/filters/AusbauFilters/__snapshots__/AusbauFilters.test.js.snap
  src/layers/AusbauLayer/AusbauLayer.js
  src/layers/AusbauLayer/AusbauLayer.test.js
Labels: 1.3
