Repository geops/trafimage-maps, pull requests merged in 2020-05, with the labels that each got.

#668 Overlay correction for v3 style
  package.json
  src/layers/BehigLayer/BehigLayer.js
  src/layers/layerHelper.js
Labels: hotfix

#671 Merge master into handicap
  package.json
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap
Labels: staging

#664 Use netzkarte and infra v3 layers
  package.json
  src/config/layers.js
  src/examples/Casa/topic.js
  src/layers/BehigLayer/BehigLayer.js
  src/layers/layerHelper.js
Labels: hotfix

#677 Fix baselayer style filter for netzkarte v3
  src/components/TopicLoader/TopicLoader.js
  src/config/layers.js
Labels: hotfix

#676 Handicap popup: Restrict links to max width and use text-overflow ellipsis
  src/popups/HandicapPopup/HandicapPopup.scss
Labels: hotfix

#673 Set apiKey for layers in TopicLoader...
  package.json
  src/components/TopicLoader/TopicLoader.js
  src/config/topics.js
  yarn.lock
Labels: hotfix

#678 WIP: Lucien/lazy load fix
  package.json
  src/WebComponent.js
  src/menus/TrackerMenu/TrackerMenu.js
  yarn.lock
Labels: hotfix

#681 Re-intialize click on layers change
  src/menus/TrackerMenu/TrackerMenu.js
Labels: hotfix

#683 CASA routes start/end style
  src/examples/Casa/README.md
  src/img/finish_flag.svg
  src/layers/CasaLayer/CasaLayer.js
  src/layers/RouteLayer/RouteLayer.js
  src/layers/RouteLayer/RouteLayer.test.js
Labels: CASA

#682 Add kilometrage layer and popup
  package.json
  src/WebComponent.scss
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureInformation/FeatureInformation.scss
  src/components/FeatureInformation/FeatureInformation.test.js
  src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap
  src/components/Map/Map.js
  src/components/TopicLoader/TopicLoader.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/layers.js
  src/config/topics.js
  src/layers/KilometrageLayer/KilometrageLayer.js
  src/layers/KilometrageLayer/index.js
  src/popups/ConstructionPopup/ConstructionPopup.scss
  src/popups/HandicapPopup/HandicapPopup.scss
  src/popups/KilometragePopup/KilometragePopup.js
  src/popups/KilometragePopup/KilometragePopup.scss
  src/popups/KilometragePopup/index.js
  src/popups/index.js
  yarn.lock
Labels: 1.1

#691 Update react-spatial to 0.3.3
  package.json
  src/config/layers.js
  src/layers/MapboxStyleLayer/MapboxStyleLayer.js
  yarn.lock
Labels: 1.1

#694 react-spatial BaseLayerSwitcher updates
  package.json
  src/components/TrafimageMaps/TrafimageMaps.scss
  yarn.lock
Labels: 1.1

#696 Upgrade react-spatial with Switcher fix
  package.json
  yarn.lock
Labels: 1.1

#697 Release 1.1 Switcher box-shadow
  src/components/TrafimageMaps/TrafimageMaps.scss
Labels: 1.1

#693 Doesn't load the web component if there is no topics for a specific appName.
  src/WebComponent.js
  src/components/TopicLoader/TopicLoader.js
  src/config/topics.js
Labels: 1.1
