Repository geops/trafimage-maps, pull requests merged in 2020-07, with the labels that each got.

#719 Upgrade react-spatial and use getRenderedTrajectories
  package.json
  src/WebComponent.scss
  src/components/MapAccessibility/MapAccessibility.js
  src/config/layers.js
  src/examples/Punctuality/README.md
  src/menus/TrackerMenu/TrackerMenu.js
  yarn.lock
Labels: hotfix

#728 Lucien/casa on ie
  src/img/finish_flag.png
  src/layers/CasaLayer/CasaLayer.js
  src/layers/RouteLayer/RouteLayer.js
  src/layers/RouteLayer/RouteLayer.test.js
Labels: hotfix

#740 Remove MapAccessibility & LevelLayer from Layers docu
  src/components/MapAccessibility/MapAccessibility.js
  src/layers/LevelLayer/LevelLayer.js
Labels: hotfix

#738 Initial commit to add hover effect on parks layer
  src/config/layers.js
  src/layers/ParksLayer/ParksLayer.js
  src/layers/ParksLayer/index.js
  yarn.lock
Labels: 1.2

#743 Circle markers on start and end of routes only
  src/layers/RouteLayer/RouteLayer.js
  src/layers/RouteLayer/RouteLayer.test.js
Labels: hotfix

#732 Release 1.2.0
  README.md
  package.json
  src/WebComponent.scss
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureInformation/FeatureInformation.test.js
  src/components/LayerInfosDialog/LayerInfosDialog.test.js
  src/components/Map/Map.js
  src/components/MapAccessibility/MapAccessibility.js
  src/components/Permalink/Permalink.js
  src/components/Permalink/Permalink.test.js
  src/components/TopicElements/TopicElements.js
  src/components/TopicLoader/TopicLoader.js
  src/components/TopicMenu/TopicMenu.js
  src/components/TopicsMenuHeader/TopicsMenuHeader.js
  src/components/TrafimageMaps/TrafimageMaps.js
  src/config/layers.js
  src/examples/Punctuality/README.md
  src/examples/Punctuality/layers.js
  src/layers/BehigLayer/BehigLayer.js
  src/layers/CasaLayer/CasaLayer.js
  src/layers/ConstructionLayer/ConstructionLayer.js
  src/layers/HandicapLayer/HandicapLayer.js
  src/layers/KilometrageLayer/KilometrageLayer.js
  src/layers/LevelLayer/LevelLayer.js
  src/layers/MapboxStyleLayer/MapboxStyleLayer.js
  src/layers/ParksLayer/ParksLayer.js
  src/layers/ParksLayer/index.js
  src/layers/TrafimageGeoServerWMSLayer/TrafimageGeoServerWMSLayer.js
  src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
  src/layers/ZweitausbildungAbroadLayer/ZweitausbildungAbroadLayer.js
  src/layers/ZweitausbildungPoisLayer/ZweitausbildungPoisLayer.js
  src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js
  src/layers/ZweitausbildungRoutesLayer/ZweitausbildungRoutesLayer.js
  src/menus/TrackerMenu/TrackerMenu.js
  src/popups/NetzkartePopup/NetzkartePopup.js
  src/searches/StopFinder/StopFinder.js
  styleguide.config.js
  yarn.lock
Labels: 1.2

#745 Change handicap translations
  src/components/Dialog/Dialog.scss
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/HandicapLayerInfo/HandicapLayerInfo.js
Labels: staging

#747 Hotfix the search clear button
  src/components/Search/Search.scss
Labels: hotfix

#748 Clean loading event mess
  src/__mocks__/mapbox-gl.js
  src/config/layers.js
  src/layers/MapboxStyleLayer/MapboxStyleLayer.js
  src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
Labels: hotfix
