Repository geops/trafimage-maps, pull requests merged in 2020-09, with the labels that each got.

#790 Raise topic menu max height
  src/components/TopicsMenu/TopicsMenu.scss
Labels: trafimage-release-immo-0.1

#797 Add configurable url to RouteLayer and ZoneLayer
  src/layers/RouteLayer/RouteLayer.js
  src/layers/ZoneLayer/ZoneLayer.js
Labels: hotfix

#792 Initial commit for new construction Layer
  src/config/layers.js
  src/config/topics.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/ConstructionFertigstellungLayerInfo/ConstructionFertigstellungLayerInfo.js
  src/layerInfos/ConstructionFertigstellungLayerInfo/index.js
  src/layerInfos/index.js
  src/layers/ConstructionLayer/ConstructionLayer.js
  src/layers/ConstructionLayer/index.js
  src/popups/ConstructionPopup/ConstructionPopup.js
Labels: trafimage-maps-release-bauprojekte-0.9

#802 Construction: Move layer and add info texts
  src/components/TrafimageMaps/TrafimageMaps.js
  src/config/layers.js
  src/config/topics.js
Labels: 1.3

#803 Fix enable tracking
  src/components/TrafimageMaps/TrafimageMaps.js
  src/components/TrafimageMaps/TrafimageMaps.test.js
Labels: 1.2, hotfix
