Repository geops/trafimage-maps, pull requests merged in 2020-11, with the labels that each got.

#833 CASA Updates + Zoom button disable
  package.json
  src/examples/Casa/casa.css
  yarn.lock
Labels: hotfix

#838 webcomponent Fix
  package.json
  src/WebComponent.js
  webComponent.html
Labels: hotfix

#794 WIP: Release 1.3
  cypress.json
  package.json
  src/components/Collapsible/Collapsible.js
  src/components/TopicMenu/TopicMenu.js
  src/components/TopicMenu/TopicMenu.scss
  src/components/TrafimageMaps/TrafimageMaps.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/layers.js
  src/config/topics.js
  src/examples/Casa/casa.css
  src/filters/AusbauFilters/AusbauFilters.js
  src/filters/AusbauFilters/AusbauFilters.test.js
  src/filters/AusbauFilters/__snapshots__/AusbauFilters.test.js.snap
  src/filters/AusbauFilters/index.js
  src/filters/index.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/ConstructionFertigstellungLayerInfo/ConstructionFertigstellungLayerInfo.js
  src/layerInfos/ConstructionFertigstellungLayerInfo/index.js
  src/layerInfos/index.js
  src/layers/AusbauLayer/AusbauLayer.js
  src/layers/AusbauLayer/AusbauLayer.test.js
  src/layers/AusbauLayer/index.js
  src/layers/ConstructionLayer/ConstructionLayer.js
  src/layers/ConstructionLayer/index.js
  src/layers/TrafimageMapboxLayer/TrafimageMapboxLayer.js
  src/popups/ConstructionPopup/ConstructionPopup.js
  src/themes/default.js
  webComponent.html
  yarn.lock
Labels: 1.3

#840 Use copyright footer in RouteScheduler
  package.json
  src/components/Footer/Footer.scss
  src/components/Link/Link.scss
  src/components/Search/Search.scss
  src/components/Share/Share.scss
  src/components/TopicMenu/TopicMenu.scss
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/menus/TrackerMenu/TrackerMenu.scss
  src/popups/HandicapPopup/HandicapPopup.scss
  yarn.lock
Labels: hotfix

#841 CASA zoom button fix
  src/examples/Casa/casa.css
Labels: bug
