Repository geops/trafimage-maps, pull requests merged in 2020-04, with the labels that each got.

#601 Use rs-BaseLayerSwitcher
  package.json
  src/WebComponent.scss
  src/components/TopicElements/TopicElements.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/layers.js
  src/config/topics.js
  src/examples/Casa/topic.js
  src/img/landeskarte.png
  src/img/landeskarte_grau.png
  src/img/luftbild.png
  src/img/netzkarte.png
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  yarn.lock
Labels: 1.1

#616 Lucien/topic collapser
  src/components/TopicMenu/TopicMenu.js
Labels: hotfix

#593 maxExtent parameter
  package.json
  public/index.html
  src/README.md
  src/WebComponent.js
  src/components/Map/Map.js
  src/components/TrafimageMaps/TrafimageMaps.js
  src/model/map/actions.js
  src/model/map/reducers.js
  yarn.lock
Labels: 1.0.8

#600 Add login redirect
  package.json
  public/index.html
  src/WebComponent.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/Header.test.js
  src/components/Header/__snapshots__/Header.test.js.snap
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/components/Login/Login.test.js
  src/components/Login/__snapshots__/Login.test.js.snap
  src/components/Login/index.js
  src/components/Permalink/Permalink.js
  src/components/Share/Share.js
  src/components/TopicLoader/TopicLoader.js
  src/model/app/actions.js
  src/model/app/reducers.js
  src/setupTests.js
  src/utils/redirectHelper.js
  src/utils/redirectHelper.test.js
Labels: 1.0.8

#633 WIP Add Manual link in ShareMenu
  src/components/Share/Share.js
  src/components/Share/Share.scss
  src/components/Share/Share.test.js
  src/lang/fr.json
  src/lang/it.json
Labels: 1.0.8

#645 Use node 12 by default
  .github/workflows/nodejs.yml
  .nvmrc
  cypress/integration/Barrierfree.spec.js
Labels: hotfix

#640 FeatureInformation: Don't put the padding on body but on the child
  src/components/FeatureInformation/FeatureInformation.scss
Labels: hotfix

#638 [WIP] Gevos/zweitausbildung patches
  src/components/FeatureInformation/FeatureInformation.scss
  src/components/IconList/IconList.js
  src/components/IconList/IconList.scss
  src/i18n.js
Labels: 1.0.8

#646 Ability to pass custom resolution/generalisation
  src/layers/BehigLayer/BehigLayer.js
  src/layers/layerHelper.js
  src/layers/layerHelper.test.js
  src/searches/Lines/Lines.js
  yarn.lock
Labels: hotfix

#648 Gevos/zweitausbildung: use variables from properties instead of env
  src/WebComponent.js
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureMenu/FeatureMenu.js
  src/components/LayerInfosDialog/LayerInfosDialog.js
  src/components/MainDialog/MainDialog.js
  src/components/Popup/Popup.js
  src/components/TopicElements/TopicElements.js
  src/components/TopicLoader/TopicLoader.js
  src/components/TrafimageMaps/TrafimageMaps.js
  src/layerInfos/BehigLayerInfo/BehigLayerInfo.js
  src/layerInfos/BehigTopicInfo/BehigTopicInfo.js
  src/layerInfos/ConstructionLayerInfo/ConstructionLayerInfo.js
  src/layerInfos/PunctualityLayerInfo/PunctualityLayerInfo.js
  src/layerInfos/TarifverbundkarteTopicInfo/TarifverbundkarteTopicInfo.js
  src/layerInfos/ZweitausbildungLayerInfo/ZweitausbildungLayerInfo.js
  src/layerInfos/ZweitausbildungRoutesSubLayerInfo/ZweitausbildungRoutesSubLayerInfo.js
  src/layerInfos/ZweitausbildungSubLayerInfo/ZweitausbildungSubLayerInfo.js
  src/layers/BehigLayer/BehigLayer.js
  src/layers/ConstructionLayer/ConstructionLayer.js
  src/layers/ZweitausbildungAbroadLayer/ZweitausbildungAbroadLayer.js
  src/layers/ZweitausbildungPoisLayer/ZweitausbildungPoisLayer.js
  src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js
  src/popups/DeparturePopup/DeparturePopup.js
  src/popups/DeparturePopup/DeparturePopupContent.js
  src/popups/DeparturePopup/DestinationInput.js
  src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.js
  src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.js
Labels: 1.0.8

#647 Gevos/zweitausbildung fix hidden topic
  package.json
  public/index.html
  src/components/TopicLoader/TopicLoader.js
  yarn.lock
Labels: 1.0.8

#651 Fix Departure popup styling...
  src/popups/DeparturePopup/DeparturePopupContent.scss
Labels: 1.0.8

#652 Zweitausbildung: Fix listed features in tourist routes popup
  src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js
  src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.js
Labels: 1.0.8

#641 Dialog height responsive on mobile, avoid css overwrite with important
  package.json
  src/components/Dialog/Dialog.scss
  src/components/LayerInfosDialog/LayerInfosDialog.js
  src/components/LayerInfosDialog/__snapshots__/LayerInfosDialog.test.js.snap
  src/components/MainDialog/MainDialog.js
  src/components/TopicElements/TopicElements.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/model/app/actions.js
  src/model/app/reducers.js
  yarn.lock
Labels: 1.0.8

#654 Zweitausbildung: Remove use of create portal
  src/components/IconList/IconList.js
  src/components/IconList/IconList.scss
  src/layers/ZweitausbildungRoutesHighlightLayer/ZweitausbildungRoutesHighlightLayer.js
Labels: 1.0.8

#617 Use netzkarte_eisenbahninfrastruktur_v2 style
  src/config/layers.js
Labels: hotfix, staging

#657 Zweitausbildung: Replace link to Karte D
  src/layers/ZweitausbildungAbroadLayer/FeatureCollection.json
Labels: 1.0.8

#658 Zweitausbildung: Restrict max zoom to 13
  src/config/topics.js
Labels: 1.0.8

#659 Fix handicap overlays (resolved merge conflict for release branch)
  src/config/layers.js
  src/layers/HandicapLayer/HandicapLayer.js
  src/layers/layerHelper.js
Labels: 1.0.8

#661 Zweitausbildung: Replace link to Karte D (merge into release branch)
  src/layers/ZweitausbildungAbroadLayer/FeatureCollection.json
Labels: 1.0.8

#662 Zweitausbildung: Restrict max zoom to 13 (merge into release branch)
  src/config/topics.js
Labels: 1.0.8

#660 Merge master into release-1.0.8
  src/config/layers.js
Labels: 1.0.8

#663 Resolved merge conflict from lazy-loading-topics into release-1.0.8
  .env
  package.json
  src/WebComponent.js
  src/components/FeatureInformation/FeatureInformation.js
  src/components/LayerInfosDialog/LayerInfosDialog.js
  src/components/Search/Search.scss
  src/components/TopicLoader/TopicLoader.js
  src/components/TopicMenu/TopicMenu.js
  src/components/TopicMenu/TopicMenu.scss
  src/components/TopicsMenuHeader/TopicsMenuHeader.js
  src/components/TopicsMenuHeader/TopicsMenuHeader.scss
  src/components/TrafimageMaps/TrafimageMaps.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/topics.js
  src/globals.scss
  src/layerInfos/InfoFPWTopicInfo/InfoFPWTopicInfo.js
  src/layerInfos/InfoFPWTopicInfo/index.js
  src/layerInfos/MobzTopicInfo/MobzTopicInfo.js
  src/layerInfos/MobzTopicInfo/index.js
  src/layerInfos/index.js
  src/model/app/actions.js
  src/model/app/reducers.js
Labels: 1.0.8
