Repository geops/trafimage-maps, pull requests merged in 2020-06, with the labels that each got.

#701 Switcher test feedback updates
  package.json
  src/components/MapControls/MapControls.scss
  src/components/TopicElements/TopicElements.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/layers.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  yarn.lock
Labels: 1.1

#702 Fix Pan on mobile
  package.json
  src/globals.scss
  yarn.lock
Labels: 1.1

#703 Fix typo in coordinate system name, rename CH1093 to CH1903 etc.
  src/components/Footer/Footer.js
Labels: hotfix

#705 Test header elements with cypress
  cypress/integration/Header.spec.js
Labels: 1.1

#706 Reduce station link in netzkarte popup
  src/components/MapControls/MapControls.scss
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/popups/NetzkartePopup/NetzkartePopup.js
Labels: 1.1

#709 IE font fix
  package.json
  src/WebComponent.scss
  src/components/TrafimageMaps/TrafimageMaps.scss
Labels: hotfix

#712 Remove topic dfa in new WKP
  package.json
  src/config/topics.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
Labels: hotfix

#713 Merge master into handicap
  package.json
  src/WebComponent.scss
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/topics.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
Labels: staging

#711 Map accessibility component
  src/components/Map/Map.js
  src/components/MapAccessibility/MapAccessibility.js
  src/components/MapAccessibility/index.js
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/layers.js
Labels: hotfix

#717 Improve a11y selection
  src/components/MapAccessibility/MapAccessibility.js
  src/components/TopicElements/TopicElements.js
Labels: hotfix

#718 Fix css to only blink the map, when focusing with tab
  src/components/TrafimageMaps/TrafimageMaps.scss
Labels: hotfix
