Repository geops/trafimage-maps, pull requests merged in 2022-01, with the labels that each got.

#946 Beleuchtungsstärken topic
  .github/workflows/cypress.yml
  cypress/integration/Barrierfree.spec.js
  cypress/integration/Handicap.spec.js
  package.json
  public/index.html
  src/WebComponent.scss
  src/components/Dialog/Dialog.js
  src/config/layers.js
  src/config/topics.js
  src/img/LightIcon/LightIcon.js
  src/img/LightIcon/index.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/BeleuchtungLayerInfo/BeleuchtungLayerInfo.js
  src/layerInfos/BeleuchtungLayerInfo/index.js
  src/layerInfos/BeleuchtungLayerInfo/lightingMapping.js
  src/layerInfos/BeleuchtungTopicInfo/BeleuchtungLegende.js
  src/layerInfos/BeleuchtungTopicInfo/BeleuchtungTopicInfo.js
  src/layerInfos/BeleuchtungTopicInfo/index.js
  src/layerInfos/MapsGeoAdminLayerInfo/MapsGeoAdminLayerInfo.js
  src/layerInfos/MapsGeoAdminLayerInfo/MapsGeoAdminLayerInfo.scss
  src/layerInfos/MapsGeoAdminLayerInfo/index.js
  src/layerInfos/index.js
  src/layers/BeleuchtungsLayer/BeleuchtungsLayer.js
  src/layers/BeleuchtungsLayer/index.js
  src/layers/MapsGeoAdminLayer/MapsGeoAdminLayer.js
  src/layers/MapsGeoAdminLayer/index.js
  src/layers/index.js
  src/popups/BeleuchtungsPopup/BeleuchtungsPopup.js
  src/popups/BeleuchtungsPopup/index.js
  src/popups/MapsGeoAdminPopup/MapsGeoAdminPopup.js
  src/popups/MapsGeoAdminPopup/MapsGeoAdminPopup.scss
  src/popups/MapsGeoAdminPopup/index.js
  src/popups/index.js
  yarn.lock
Labels: feature

#963 Fix app interaction while Dialog is open
  cypress/integration/Header.spec.js
  src/WebComponent.scss
  src/components/Dialog/Dialog.js
  src/components/LanguageSelect/LanguageSelect.js
  src/components/LanguageSelect/LanguageSelect.scss
  src/components/ProjectionSelect/ProjectionSelect.js
  src/components/ProjectionSelect/ProjectionSelect.scss
  src/components/Select/SBBSelect.js
  src/components/Select/Select.js
  src/components/Select/SingleValue.js
  src/components/Select/SingleValue.scss
  src/img/minus.svg
  src/img/plus.svg
  src/lang/en.json
  src/layerInfos/MapsGeoAdminLayerInfo/MapsGeoAdminLayerInfo.scss
  src/menus/ExportMenu/ExportMenu.js
  src/popups/MapsGeoAdminPopup/MapsGeoAdminPopup.scss
  src/popups/RegionenkarteSegmentPopup/Av.js
  src/popups/RegionenkarteSegmentPopup/Region.js
  src/themes/default.js
Labels: bug

#964 Draft: Expand BAFU layers
  package.json
  src/config/layers.js
  src/config/topics.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/MapsGeoAdminLayerInfo/MapsGeoAdminLayerInfo.scss
  src/popups/MapsGeoAdminPopup/MapsGeoAdminPopup.js
Labels: feature

#967 Improve Select
  cypress/integration/Header.spec.js
  src/components/LanguageSelect/LanguageSelect.js
  src/components/ProjectionSelect/ProjectionSelect.js
  src/components/Select/Select.js
  src/components/TopicMenu/TopicMenu.js
  src/components/TopicMenu/TopicMenu.scss
  src/components/TrafimageMaps/TrafimageMaps.scss
  src/config/layers.js
  src/lang/fr.json
Labels: bug

#965 Fixes
  .env
  cypress/integration/Search.spec.js
  src/components/Dialog/Dialog.js
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureInformation/FeatureInformation.test.js
  src/components/FeatureInformation/__snapshots__/FeatureInformation.test.js.snap
  src/components/InfosButton/InfosButton.test.js
  src/components/Overlay/Overlay.js
  src/components/Permalink/Permalink.js
  src/components/Search/Search.js
  src/components/Search/Search.test.js
  src/config/layers.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/HandicapLayerInfo/HandicapLayerInfo.js
  src/layers/PlatformsLayer/PlatformsLayer.js
  src/layers/StationsLayer/StationsLayer.js
  src/layers/layerHelper.js
  src/layers/layerHelper.test.js
  src/popups/DeparturePopup/DeparturePopup.js
  src/popups/DeparturePopup/DeparturePopupContent.js
  src/popups/HandicapPopup/HandicapPopup.scss
  src/popups/NetzkartePopup/NetzkartePopup.js
  src/popups/NetzkartePopup/NetzkartePopup.test.js
  src/popups/StationPopup/StationPopup.js
  src/searches/Lines/Lines.js
  src/searches/StopFinder/StopFinder.js
  src/utils/getGreaterNumber.js
  src/utils/getGreaterNumber.test.js
Labels: hotfix

#942 Add cookies consent properties
  src/WebComponent.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.test.js
  src/components/TrafimageMaps/TrafimageMaps.js
  src/model/app/actions.js
  src/model/app/reducers.js
Labels: hotfix

#971 Use overlay by default instead of popup
  package.json
  src/components/FeatureInformation/FeatureInformation.js
  src/components/FeatureInformation/FeatureInformation.test.js
  src/config/layers.js
  src/popups/ZweitausbildungPoisPopup/ZweitausbildungPoisPopup.scss
  src/popups/ZweitausbildungRoutesPopup/ZweitausbildungRoutesPopup.scss
Labels: hotfix
