Repository geops/trafimage-maps, pull requests merged in 2024-05, with the labels that each got.

#1169 fix: request new data only when previous request has ended and add a request timeout
  src/layers/MesswagenLayer/MesswagenLayer.js
  src/layers/MesswagenLayer/MesswagenLayer.test.js
Labels: bug

#1170 fix(isb): rename Berner Oberland Bahnen AG to Berner Oberland Bahnen
  src/config/ch.sbb.isb/index.js
Labels: hotfix

#1163 feat(funkmesswagen): add photo layer for Funkmesswagen topic
  .env
  src/components/Dialog/Dialog.js
  src/components/ExportButton/ExportButton.js
  src/components/Header/__snapshots__/Header.test.js.snap
  src/components/LanguageSelect/LanguageSelect.js
  src/components/LegendCircle/LegendCircle.js
  src/components/MainDialog/MainDialog.js
  src/components/MapControls/MapControls.js
  src/components/Overlay/Overlay.js
  src/components/PhotoCarusel/PhotoCarusel.js
  src/components/PhotoCarusel/PhotoCarusel.test.js
  src/components/PhotoCarusel/index.js
  src/components/ProjectionSelect/ProjectionSelect.js
  src/components/Search/Search.js
  src/config/ch.sbb.direktverbindungen/DvFeatureInfo/DvFeatureInfo.js
  src/config/ch.sbb.direktverbindungen/DvFeatureInfoTitle/DvFeatureInfoTitle.js
  src/config/ch.sbb.direktverbindungen/DvLineInfo/DvLineInfo.js
  src/config/ch.sbb.direktverbindungen/DvLineTitle/DvLineTitle.js
  src/config/ch.sbb.funkmesswagen/index.js
  src/config/topics.js
  src/filters/AusbauFilters/__snapshots__/AusbauFilters.test.js.snap
  src/img/LightIcon/LightIcon.js
  src/img/LightIcon/index.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
  src/layerInfos/BeleuchtungTopicInfo/BeleuchtungLegende.js
  src/layerInfos/MesswagenPhotosLayerInfo/MesswagenPhotosLayerInfo.js
  src/layerInfos/MesswagenPhotosLayerInfo/index.js
  src/layerInfos/TarifverbundkarteTopicInfo/TarifVerbundLegend.js
  src/layerInfos/index.js
  src/menus/DirektverbindungenMenu/DvLayerSwitcher.js
  src/menus/DirektverbindungenMenu/DvMenu.js
  src/menus/GaExportMenu/GaExportMapButton.js
  src/menus/IframeMenu/IframeMenu.js
  src/menus/RailplusMenu/RailplusMenu.js
  src/menus/StsMenu/StsMenu.js
  src/menus/StsMenu/StsValidityFeatureInfo.js
  src/popups/BeleuchtungsPopup/BeleuchtungsPopup.js
  src/popups/MesswagenPhotosPopup/MesswagenPhotosPopup.js
  src/popups/MesswagenPhotosPopup/index.js
  src/popups/index.js
  src/themes/default.js
  src/utils/useHasScreenSize.js
  src/utils/useHighlightLayer.js
  src/utils/usePanCenterFeature.js
Labels: feature
