Repository geops/trafimage-maps, pull requests merged in 2024-02, with the labels that each got.

#1142 fix(handicap): update display of alternative transport in handicap overlay
  src/popups/StopPlacePopup/StopPlacePopup.js
  src/popups/StopPlacePopup/StopPlacePopup.test.js
Labels: hotfix

#1147 fix(railplus): update address in railplus PDF legends
  src/img/railplus_legend_de.url.svg
  src/img/railplus_legend_fr.url.svg
  src/img/railplus_legend_it.url.svg
Labels: hotfix

#1149 fix(netzkarte): use metadata tags for station layer source update instead of layer.id/layer.source-layer
  src/config/ch.sbb.netzkarte/index.js
  src/layers/StationsLayer/StationsLayer.js
Labels: bug, hotfix

#1150 fix: use the good generalization level on highlight trajectory
  package.json
  yarn.lock
Labels: bug
