Repository geops/trafimage-maps, pull requests merged in 2024-03, with the labels that each got.

#1153 fix(Haltekanten): remove stop_positions from StationsLayer, use metadata tag in PlatformsLayer
  src/layers/PlatformsLayer/PlatformsLayer.js
  src/layers/StationsLayer/StationsLayer.js
Labels: bug, hotfix

#1154 fix(tarifverbundkarte): add Tarifverbund Klosters to PDF legend
  src/img/tarifverbund_legend.url.svg
Labels: enhancement

#1156 fix(overlay): remove features from overlay when deactivating layers
  src/components/FeatureInformation/FeatureInformation.js
  src/utils/useUpdateFeatureInfoOnLayerToggle.js
  src/utils/useUpdateFeatureInfoOnLayerToggle.test.js
Labels: bug

#1157 fix(regionenkarte): make regionenkarte legend reusable as its own component
  src/layerInfos/RegionenkartePublicLayerInfo/RegionenkarteLegend.js
  src/layerInfos/RegionenkartePublicLayerInfo/RegionenkarteLegend.test.js
  src/layerInfos/RegionenkartePublicLayerInfo/RegionenkartePublicLayerInfo.js
  src/layerInfos/TarifverbundkarteTopicInfo/TarifverbundLegend.test.js
Labels: enhancement

#1155 fix: use also the devicePixelRatio to size properly the scale bar in pdf
  src/components/ExportButton/ExportButton.js
  src/utils/exportUtils.js
  src/utils/fontUtils.js
Labels: bug
