Repository geops/trafimage-maps, pull requests merged in 2024-08, with the labels that each got.

#1184 fix(railplus): add overflow and max-hight to railplus popup to fix scroll
  src/lang/fr.json
  src/menus/RailplusMenu/RailplusMenu.js
  src/popups/RailplusPopup/RailplusPopup.js
Labels: bug, hotfix

#1185 fix(eisenbahninfrastruktur): increase maxZoom for topics with visible rail project labels
  src/config/topics.js
  src/lang/de.json
  src/lang/en.json
  src/lang/fr.json
  src/lang/it.json
Labels: hotfix

#1189 fix: ceil the arrival delay and floor the departure delay
  .husky/commit-msg
  .husky/post-checkout
  .husky/post-merge
  .husky/post-rebase
  .husky/pre-commit
  package.json
  src/popups/PunctualityPopup/PunctualityPopup.js
  yarn.lock
Labels: bug
